# Generated by Django 4.2.13 on 2024-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qual', models.CharField(max_length=200)),
                ('certification', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phno', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('pdesc', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=200)),
                ('pimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
