# Generated by Django 4.2.13 on 2024-05-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pdesc',
            new_name='project_desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pimage',
            new_name='project_image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pname',
            new_name='project_name',
        ),
    ]
